// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject.WorkerPackage;

//
// IDL:CorbaObject/Worker/longList:1.0
//
final public class longListHolder implements org.omg.CORBA.portable.Streamable
{
    public int[] value;

    public
    longListHolder()
    {
    }

    public
    longListHolder(int[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = longListHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        longListHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return longListHelper.type();
    }
}
