// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/CompteDeLiquiditeList:1.0
//
final public class CompteDeLiquiditeListHolder implements org.omg.CORBA.portable.Streamable
{
    public CompteDeLiquidite[] value;

    public
    CompteDeLiquiditeListHolder()
    {
    }

    public
    CompteDeLiquiditeListHolder(CompteDeLiquidite[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = CompteDeLiquiditeListHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        CompteDeLiquiditeListHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return CompteDeLiquiditeListHelper.type();
    }
}
