// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/CompteDeLiquidite:1.0
//
final public class CompteDeLiquiditeHelper
{
    public static void
    insert(org.omg.CORBA.Any any, CompteDeLiquidite val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static CompteDeLiquidite
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[3];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "numeroCompte";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "soldeCourant";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "soldeDisponible";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            typeCode_ = orb.create_struct_tc(id(), "CompteDeLiquidite", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:CorbaObject/CompteDeLiquidite:1.0";
    }

    public static CompteDeLiquidite
    read(org.omg.CORBA.portable.InputStream in)
    {
        CompteDeLiquidite _ob_v = new CompteDeLiquidite();
        _ob_v.numeroCompte = in.read_string();
        _ob_v.soldeCourant = in.read_float();
        _ob_v.soldeDisponible = in.read_float();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, CompteDeLiquidite val)
    {
        out.write_string(val.numeroCompte);
        out.write_float(val.soldeCourant);
        out.write_float(val.soldeDisponible);
    }
}
