// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/CompteDeTitre:1.0
//
/***/

final public class CompteDeTitre implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _ob_id = "IDL:CorbaObject/CompteDeTitre:1.0";

    public
    CompteDeTitre()
    {
    }

    public
    CompteDeTitre(String numeroCompte,
                  Societe[] societeListe,
                  Ordre[] ordreListe)
    {
        this.numeroCompte = numeroCompte;
        this.societeListe = societeListe;
        this.ordreListe = ordreListe;
    }

    public String numeroCompte;
    public Societe[] societeListe;
    public Ordre[] ordreListe;
}
