// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/CompteDeTitre:1.0
//
final public class CompteDeTitreHolder implements org.omg.CORBA.portable.Streamable
{
    public CompteDeTitre value;

    public
    CompteDeTitreHolder()
    {
    }

    public
    CompteDeTitreHolder(CompteDeTitre initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = CompteDeTitreHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        CompteDeTitreHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return CompteDeTitreHelper.type();
    }
}
