// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/CourtierForParticulier:1.0
//
/***/

public interface CourtierForParticulierOperations
{
    //
    // IDL:CorbaObject/CourtierForParticulier/checkLogin:1.0
    //
    /***/

    Succes
    checkLogin(String loginCourtier,
               String loginParticulier,
               String motDePasse);

    //
    // IDL:CorbaObject/CourtierForParticulier/EmettreOrdre:1.0
    //
    /***/

    Succes
    EmettreOrdre(String loginCourtier,
                 String loginParticulier,
                 Ordre unordre);

    //
    // IDL:CorbaObject/CourtierForParticulier/TransfererLiquidite:1.0
    //
    /***/

    Succes
    TransfererLiquidite(String loginCourtier,
                        Virement unvirement,
                        String loginParticulier);

    //
    // IDL:CorbaObject/CourtierForParticulier/TransfererTitre:1.0
    //
    /***/

    Succes
    TransfererTitre(String loginCourtier,
                    String loginParticulier,
                    String numeroSociete,
                    int nombreTitre,
                    String numeroCompteDebiteur,
                    String numeroCompteCrediteur);

    //
    // IDL:CorbaObject/CourtierForParticulier/ConsulterBourse:1.0
    //
    /***/

    Evolution
    ConsulterBourse(String numeroSociete);

    //
    // IDL:CorbaObject/CourtierForParticulier/getListSociete:1.0
    //
    /***/

    Societe[]
    getListSociete();

    //
    // IDL:CorbaObject/CourtierForParticulier/getListSocietePourUnParticulier:1.0
    //
    /***/

    Societe[]
    getListSocietePourUnParticulier(String loginCourtier,
                                    String numeroParticulier);

    //
    // IDL:CorbaObject/CourtierForParticulier/getListCompteTitre:1.0
    //
    /***/

    CompteDeTitre[]
    getListCompteTitre(String loginCourtier,
                       String numeroParticulier,
                       String numeroCompteDeLiquidites);

    //
    // IDL:CorbaObject/CourtierForParticulier/getListCompteLiquidite:1.0
    //
    /***/

    CompteDeLiquidite[]
    getListCompteLiquidite(String loginCourtier,
                           String numeroParticulier);

    //
    // IDL:CorbaObject/CourtierForParticulier/getListVirement:1.0
    //
    /***/

    Virement[]
    getListVirement(String numeroCompteLiquidite,
                    DateStruct date);

    //
    // IDL:CorbaObject/CourtierForParticulier/getListOrdre:1.0
    //
    /***/

    Ordre[]
    getListOrdre(String numeroCompteTitre,
                 DateStruct date);

    //
    // IDL:CorbaObject/CourtierForParticulier/getListCourtier:1.0
    //
    /***/

    String[]
    getListCourtier();
}
