// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/DateStruct:1.0
//
final public class DateStructHolder implements org.omg.CORBA.portable.Streamable
{
    public DateStruct value;

    public
    DateStructHolder()
    {
    }

    public
    DateStructHolder(DateStruct initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = DateStructHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        DateStructHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return DateStructHelper.type();
    }
}
