// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Evolution:1.0
//
final public class EvolutionHelper
{
    public static void
    insert(org.omg.CORBA.Any any, Evolution val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static Evolution
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[5];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "date";
            members[0].type = DateStructHelper.type();

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "valeur";
            members[1].type = FloatListHelper.type();

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "unesociete";
            members[2].type = SocieteHelper.type();

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "les5meilleursAchat";
            members[3].type = FloatListHelper.type();

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "les5meilleursVente";
            members[4].type = FloatListHelper.type();

            typeCode_ = orb.create_struct_tc(id(), "Evolution", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:CorbaObject/Evolution:1.0";
    }

    public static Evolution
    read(org.omg.CORBA.portable.InputStream in)
    {
        Evolution _ob_v = new Evolution();
        _ob_v.date = DateStructHelper.read(in);
        _ob_v.valeur = FloatListHelper.read(in);
        _ob_v.unesociete = SocieteHelper.read(in);
        _ob_v.les5meilleursAchat = FloatListHelper.read(in);
        _ob_v.les5meilleursVente = FloatListHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, Evolution val)
    {
        DateStructHelper.write(out, val.date);
        FloatListHelper.write(out, val.valeur);
        SocieteHelper.write(out, val.unesociete);
        FloatListHelper.write(out, val.les5meilleursAchat);
        FloatListHelper.write(out, val.les5meilleursVente);
    }
}
