// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Societe:1.0
//
final public class SocieteHelper
{
    public static void
    insert(org.omg.CORBA.Any any, Societe val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static Societe
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[5];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "numeroSociete";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "nomSociete";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "titreListe";
            members[2].type = TitreListHelper.type();

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "valeur";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_float);

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "etat";
            members[4].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_boolean);

            typeCode_ = orb.create_struct_tc(id(), "Societe", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:CorbaObject/Societe:1.0";
    }

    public static Societe
    read(org.omg.CORBA.portable.InputStream in)
    {
        Societe _ob_v = new Societe();
        _ob_v.numeroSociete = in.read_string();
        _ob_v.nomSociete = in.read_string();
        _ob_v.titreListe = TitreListHelper.read(in);
        _ob_v.valeur = in.read_float();
        _ob_v.etat = in.read_boolean();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, Societe val)
    {
        out.write_string(val.numeroSociete);
        out.write_string(val.nomSociete);
        TitreListHelper.write(out, val.titreListe);
        out.write_float(val.valeur);
        out.write_boolean(val.etat);
    }
}
