// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Societe:1.0
//
/***/

final public class Societe implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _ob_id = "IDL:CorbaObject/Societe:1.0";

    public
    Societe()
    {
    }

    public
    Societe(String numeroSociete,
            String nomSociete,
            Titre[] titreListe,
            float valeur,
            boolean etat)
    {
        this.numeroSociete = numeroSociete;
        this.nomSociete = nomSociete;
        this.titreListe = titreListe;
        this.valeur = valeur;
        this.etat = etat;
    }

    public String numeroSociete;
    public String nomSociete;
    public Titre[] titreListe;
    public float valeur;
    public boolean etat;
}
