// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/TitreList:1.0
//
final public class TitreListHolder implements org.omg.CORBA.portable.Streamable
{
    public Titre[] value;

    public
    TitreListHolder()
    {
    }

    public
    TitreListHolder(Titre[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = TitreListHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        TitreListHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return TitreListHelper.type();
    }
}
