// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Virement:1.0
//
/***/

final public class Virement implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _ob_id = "IDL:CorbaObject/Virement:1.0";

    public
    Virement()
    {
    }

    public
    Virement(DateStruct date,
             String numeroDebiteur,
             String numeroCrediteur,
             float montant)
    {
        this.date = date;
        this.numeroDebiteur = numeroDebiteur;
        this.numeroCrediteur = numeroCrediteur;
        this.montant = montant;
    }

    public DateStruct date;
    public String numeroDebiteur;
    public String numeroCrediteur;
    public float montant;
}
