//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Resource.rc
//
#define IDI_ICON1                       101
#define IDC_CURSOR1                     102
#define IDR_MENU1                       103
#define ID_HETHONG_THOAT                40001
#define ID_HETHONG_NOIKETFILENGUON      40002
#define ID_HETHONG_NOIKETCAMERA         40003
#define ID_QUATRINHXULY_TAMDUNG         40004
#define ID_QUATRINHXULY_KETTHUC         40005
#define ID_QUATRINHXULY_BATDAU          40006
#define ID_HETHONG_GHIKETQUA            40007
#define ID_HUONGDANSUDUNG_TACGIA        40008
#define ID_HUONGDANSUDUNG_TAILIEUHUONGDAN 40009
#define ID_KETQUA_TACHDOITUONG          40010
#define ID_KETQUA_DEMSODOITUONG         40011
#define ID_KETQUA_BAMDOITUONG           40012
#define ID_KETQUA_KETQUATOANBO          40013
#define ID_HUONGDANSUDUNG_CACTHUATTOANCHINH 40014

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        104
#define _APS_NEXT_COMMAND_VALUE         40015
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
