// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Client:1.0
//
/***/

public interface ClientOperations
{
    //
    // IDL:CorbaObject/Client/RenduTermine:1.0
    //
    /***/

    void
    RenduTermine(int numeroduticket,
                 String contenudelimagefinale);
}
