// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Dispatcher:1.0
//
/***/

public interface DispatcherOperations
{
    //
    // IDL:CorbaObject/Dispatcher/annulerTache:1.0
    //
    /***/

    boolean
    annulerTache(int numticket);

    //
    // IDL:CorbaObject/Dispatcher/obtenirResultatFinal:1.0
    //
    /***/

    byte[]
    obtenirResultatFinal(int numticket);

    //
    // IDL:CorbaObject/Dispatcher/commanderUnRendu:1.0
    //
    /***/

    int
    commanderUnRendu(byte[] contentpovrayfile,
                     int width,
                     int height);

    //
    // IDL:CorbaObject/Dispatcher/synchronizeCommandeDeRendu:1.0
    //
    /***/

    int
    synchronizeCommandeDeRendu(byte[] contentpovrayfile,
                               int width,
                               int height,
                               int numberticket,
                               int datedebuttache,
                               int heuredebuttache,
                               int datefintache,
                               int heurefintache);

    //
    // IDL:CorbaObject/Dispatcher/obtenirEtatAvancement:1.0
    //
    /***/

    CorbaObject.DispatcherPackage.Informations
    obtenirEtatAvancement(int numeroticket);

    //
    // IDL:CorbaObject/Dispatcher/updateFragment:1.0
    //
    /***/

    void
    updateFragment(int numticket,
                   int numfragment,
                   byte[] content);

    //
    // IDL:CorbaObject/Dispatcher/setID:1.0
    //
    /***/

    void
    setID(int IDnumber);

    //
    // IDL:CorbaObject/Dispatcher/saveNewDispatcher:1.0
    //
    /***/

    void
    saveNewDispatcher(String IOR);

    //
    // IDL:CorbaObject/Dispatcher/saveNewWorker:1.0
    //
    /***/

    void
    saveNewWorker(String IOR);

    //
    // IDL:CorbaObject/Dispatcher/saveNewClient:1.0
    //
    /***/

    void
    saveNewClient(String IOR);

    //
    // IDL:CorbaObject/Dispatcher/dearLeaderAreUStillThere:1.0
    //
    /***/

    void
    dearLeaderAreUStillThere();
}
