// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Dispatcher:1.0
//
public abstract class DispatcherPOA
    extends org.omg.PortableServer.Servant
    implements org.omg.CORBA.portable.InvokeHandler,
               DispatcherOperations
{
    static final String[] _ob_ids_ =
    {
        "IDL:CorbaObject/Dispatcher:1.0",
    };

    public Dispatcher
    _this()
    {
        return DispatcherHelper.narrow(super._this_object());
    }

    public Dispatcher
    _this(org.omg.CORBA.ORB orb)
    {
        return DispatcherHelper.narrow(super._this_object(orb));
    }

    public String[]
    _all_interfaces(org.omg.PortableServer.POA poa, byte[] objectId)
    {
        return _ob_ids_;
    }

    public org.omg.CORBA.portable.OutputStream
    _invoke(String opName,
            org.omg.CORBA.portable.InputStream in,
            org.omg.CORBA.portable.ResponseHandler handler)
    {
        final String[] _ob_names =
        {
            "annulerTache",
            "commanderUnRendu",
            "dearLeaderAreUStillThere",
            "obtenirEtatAvancement",
            "obtenirResultatFinal",
            "saveNewClient",
            "saveNewDispatcher",
            "saveNewWorker",
            "setID",
            "synchronizeCommandeDeRendu",
            "updateFragment"
        };

        int _ob_left = 0;
        int _ob_right = _ob_names.length;
        int _ob_index = -1;

        while(_ob_left < _ob_right)
        {
            int _ob_m = (_ob_left + _ob_right) / 2;
            int _ob_res = _ob_names[_ob_m].compareTo(opName);
            if(_ob_res == 0)
            {
                _ob_index = _ob_m;
                break;
            }
            else if(_ob_res > 0)
                _ob_right = _ob_m;
            else
                _ob_left = _ob_m + 1;
        }

        if(_ob_index == -1 && opName.charAt(0) == '_')
        {
            _ob_left = 0;
            _ob_right = _ob_names.length;
            String _ob_ami_op =
                opName.substring(1);

            while(_ob_left < _ob_right)
            {
                int _ob_m = (_ob_left + _ob_right) / 2;
                int _ob_res = _ob_names[_ob_m].compareTo(_ob_ami_op);
                if(_ob_res == 0)
                {
                    _ob_index = _ob_m;
                    break;
                }
                else if(_ob_res > 0)
                    _ob_right = _ob_m;
                else
                    _ob_left = _ob_m + 1;
            }
        }

        switch(_ob_index)
        {
        case 0: // annulerTache
            return _OB_op_annulerTache(in, handler);

        case 1: // commanderUnRendu
            return _OB_op_commanderUnRendu(in, handler);

        case 2: // dearLeaderAreUStillThere
            return _OB_op_dearLeaderAreUStillThere(in, handler);

        case 3: // obtenirEtatAvancement
            return _OB_op_obtenirEtatAvancement(in, handler);

        case 4: // obtenirResultatFinal
            return _OB_op_obtenirResultatFinal(in, handler);

        case 5: // saveNewClient
            return _OB_op_saveNewClient(in, handler);

        case 6: // saveNewDispatcher
            return _OB_op_saveNewDispatcher(in, handler);

        case 7: // saveNewWorker
            return _OB_op_saveNewWorker(in, handler);

        case 8: // setID
            return _OB_op_setID(in, handler);

        case 9: // synchronizeCommandeDeRendu
            return _OB_op_synchronizeCommandeDeRendu(in, handler);

        case 10: // updateFragment
            return _OB_op_updateFragment(in, handler);
        }

        throw new org.omg.CORBA.BAD_OPERATION();
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_annulerTache(org.omg.CORBA.portable.InputStream in,
                        org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        int _ob_a0 = in.read_long();
        boolean _ob_r = annulerTache(_ob_a0);
        out = handler.createReply();
        out.write_boolean(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_commanderUnRendu(org.omg.CORBA.portable.InputStream in,
                            org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        byte[] _ob_a0 = CorbaObject.DispatcherPackage.octetListHelper.read(in);
        int _ob_a1 = in.read_long();
        int _ob_a2 = in.read_long();
        int _ob_r = commanderUnRendu(_ob_a0, _ob_a1, _ob_a2);
        out = handler.createReply();
        out.write_long(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_dearLeaderAreUStillThere(org.omg.CORBA.portable.InputStream in,
                                    org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        dearLeaderAreUStillThere();
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_obtenirEtatAvancement(org.omg.CORBA.portable.InputStream in,
                                 org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        int _ob_a0 = in.read_long();
        CorbaObject.DispatcherPackage.Informations _ob_r = obtenirEtatAvancement(_ob_a0);
        out = handler.createReply();
        CorbaObject.DispatcherPackage.InformationsHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_obtenirResultatFinal(org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        int _ob_a0 = in.read_long();
        byte[] _ob_r = obtenirResultatFinal(_ob_a0);
        out = handler.createReply();
        CorbaObject.DispatcherPackage.octetListHelper.write(out, _ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_saveNewClient(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_a0 = in.read_string();
        saveNewClient(_ob_a0);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_saveNewDispatcher(org.omg.CORBA.portable.InputStream in,
                             org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_a0 = in.read_string();
        saveNewDispatcher(_ob_a0);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_saveNewWorker(org.omg.CORBA.portable.InputStream in,
                         org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        String _ob_a0 = in.read_string();
        saveNewWorker(_ob_a0);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_setID(org.omg.CORBA.portable.InputStream in,
                 org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        int _ob_a0 = in.read_long();
        setID(_ob_a0);
        out = handler.createReply();
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_synchronizeCommandeDeRendu(org.omg.CORBA.portable.InputStream in,
                                      org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        byte[] _ob_a0 = CorbaObject.DispatcherPackage.octetListHelper.read(in);
        int _ob_a1 = in.read_long();
        int _ob_a2 = in.read_long();
        int _ob_a3 = in.read_long();
        int _ob_a4 = in.read_long();
        int _ob_a5 = in.read_long();
        int _ob_a6 = in.read_long();
        int _ob_a7 = in.read_long();
        int _ob_r = synchronizeCommandeDeRendu(_ob_a0, _ob_a1, _ob_a2, _ob_a3, _ob_a4, _ob_a5, _ob_a6, _ob_a7);
        out = handler.createReply();
        out.write_long(_ob_r);
        return out;
    }

    private org.omg.CORBA.portable.OutputStream
    _OB_op_updateFragment(org.omg.CORBA.portable.InputStream in,
                          org.omg.CORBA.portable.ResponseHandler handler)
    {
        org.omg.CORBA.portable.OutputStream out = null;
        int _ob_a0 = in.read_long();
        int _ob_a1 = in.read_long();
        byte[] _ob_a2 = CorbaObject.DispatcherPackage.octetListHelper.read(in);
        updateFragment(_ob_a0, _ob_a1, _ob_a2);
        out = handler.createReply();
        return out;
    }
}
