// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Dispatcher:1.0
//
final public class DispatcherHolder implements org.omg.CORBA.portable.Streamable
{
    public Dispatcher value;

    public
    DispatcherHolder()
    {
    }

    public
    DispatcherHolder(Dispatcher initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = DispatcherHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        DispatcherHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return DispatcherHelper.type();
    }
}
