// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Worker:1.0
//
final public class WorkerHolder implements org.omg.CORBA.portable.Streamable
{
    public Worker value;

    public
    WorkerHolder()
    {
    }

    public
    WorkerHolder(Worker initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = WorkerHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        WorkerHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return WorkerHelper.type();
    }
}
