// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Worker:1.0
//
/***/

public interface WorkerOperations
{
    //
    // IDL:CorbaObject/Worker/executeJob:1.0
    //
    /***/

    void
    executeJob(byte[] contentpovrayfile,
               int[] chunkAlreadyDone,
               int chunkHeight,
               int width,
               int height,
               int ticketnumber,
               int numberoffragment);

    //
    // IDL:CorbaObject/Worker/updateJob:1.0
    //
    /***/

    void
    updateJob(int numeroticket,
              int chunkjustdone);

    //
    // IDL:CorbaObject/Worker/areUstilWorking:1.0
    //
    /***/

    boolean
    areUstilWorking();

    //
    // IDL:CorbaObject/Worker/setId:1.0
    //
    /***/

    void
    setId(int id);

    //
    // IDL:CorbaObject/Worker/wakeUp:1.0
    //
    /***/

    void
    wakeUp();

    //
    // IDL:CorbaObject/Worker/cancelTask:1.0
    //
    /***/

    void
    cancelTask(int ticket);
}
