// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject.DispatcherPackage;

//
// IDL:CorbaObject/Dispatcher/DataFinale:1.0
//
/***/

final public class DataFinale implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _ob_id = "IDL:CorbaObject/Dispatcher/DataFinale:1.0";

    public
    DataFinale()
    {
    }

    public
    DataFinale(byte[] data)
    {
        this.data = data;
    }

    public byte[] data;
}
