// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject.DispatcherPackage;

//
// IDL:CorbaObject/Dispatcher/Informations:1.0
//
/***/

final public class Informations implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _ob_id = "IDL:CorbaObject/Dispatcher/Informations:1.0";

    public
    Informations()
    {
    }

    public
    Informations(int percentageDone,
                 int startingTime,
                 int endingTime,
                 int startingDate,
                 int endingDate)
    {
        this.percentageDone = percentageDone;
        this.startingTime = startingTime;
        this.endingTime = endingTime;
        this.startingDate = startingDate;
        this.endingDate = endingDate;
    }

    public int percentageDone;
    public int startingTime;
    public int endingTime;
    public int startingDate;
    public int endingDate;
}
