// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject.DispatcherPackage;

//
// IDL:CorbaObject/Dispatcher/Informations:1.0
//
final public class InformationsHolder implements org.omg.CORBA.portable.Streamable
{
    public Informations value;

    public
    InformationsHolder()
    {
    }

    public
    InformationsHolder(Informations initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = InformationsHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        InformationsHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return InformationsHelper.type();
    }
}
