// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject.DispatcherPackage;

//
// IDL:CorbaObject/Dispatcher/Informations:1.0
//
final public class InformationsHelper
{
    public static void
    insert(org.omg.CORBA.Any any, Informations val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static Informations
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[5];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "percentageDone";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "startingTime";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "endingTime";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "startingDate";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "endingDate";
            members[4].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            typeCode_ = orb.create_struct_tc(id(), "Informations", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:CorbaObject/Dispatcher/Informations:1.0";
    }

    public static Informations
    read(org.omg.CORBA.portable.InputStream in)
    {
        Informations _ob_v = new Informations();
        _ob_v.percentageDone = in.read_long();
        _ob_v.startingTime = in.read_long();
        _ob_v.endingTime = in.read_long();
        _ob_v.startingDate = in.read_long();
        _ob_v.endingDate = in.read_long();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, Informations val)
    {
        out.write_long(val.percentageDone);
        out.write_long(val.startingTime);
        out.write_long(val.endingTime);
        out.write_long(val.startingDate);
        out.write_long(val.endingDate);
    }
}
