// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject.DispatcherPackage;

//
// IDL:CorbaObject/Dispatcher/octetList:1.0
//
final public class octetListHolder implements org.omg.CORBA.portable.Streamable
{
    public byte[] value;

    public
    octetListHolder()
    {
    }

    public
    octetListHolder(byte[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = octetListHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        octetListHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return octetListHelper.type();
    }
}
