// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/CourtierForParticulier:1.0
//
public class _CourtierForParticulierStub extends org.omg.CORBA.portable.ObjectImpl
                                         implements CourtierForParticulier
{
    private static final String[] _ob_ids_ =
    {
        "IDL:CorbaObject/CourtierForParticulier:1.0",
    };

    public String[]
    _ids()
    {
        return _ob_ids_;
    }

    final public static java.lang.Class _ob_opsClass = CourtierForParticulierOperations.class;

    //
    // IDL:CorbaObject/CourtierForParticulier/checkLogin:1.0
    //
    public Succes
    checkLogin(String _ob_a0,
               String _ob_a1,
               String _ob_a2)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("checkLogin", true);
                    out.write_string(_ob_a0);
                    out.write_string(_ob_a1);
                    out.write_string(_ob_a2);
                    in = _invoke(out);
                    Succes _ob_r = SuccesHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("checkLogin", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.checkLogin(_ob_a0, _ob_a1, _ob_a2);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/EmettreOrdre:1.0
    //
    public Succes
    EmettreOrdre(String _ob_a0,
                 String _ob_a1,
                 Ordre _ob_a2)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("EmettreOrdre", true);
                    out.write_string(_ob_a0);
                    out.write_string(_ob_a1);
                    OrdreHelper.write(out, _ob_a2);
                    in = _invoke(out);
                    Succes _ob_r = SuccesHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("EmettreOrdre", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.EmettreOrdre(_ob_a0, _ob_a1, _ob_a2);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/TransfererLiquidite:1.0
    //
    public Succes
    TransfererLiquidite(String _ob_a0,
                        Virement _ob_a1,
                        String _ob_a2)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("TransfererLiquidite", true);
                    out.write_string(_ob_a0);
                    VirementHelper.write(out, _ob_a1);
                    out.write_string(_ob_a2);
                    in = _invoke(out);
                    Succes _ob_r = SuccesHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("TransfererLiquidite", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.TransfererLiquidite(_ob_a0, _ob_a1, _ob_a2);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/TransfererTitre:1.0
    //
    public Succes
    TransfererTitre(String _ob_a0,
                    String _ob_a1,
                    String _ob_a2,
                    int _ob_a3,
                    String _ob_a4,
                    String _ob_a5)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("TransfererTitre", true);
                    out.write_string(_ob_a0);
                    out.write_string(_ob_a1);
                    out.write_string(_ob_a2);
                    out.write_long(_ob_a3);
                    out.write_string(_ob_a4);
                    out.write_string(_ob_a5);
                    in = _invoke(out);
                    Succes _ob_r = SuccesHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("TransfererTitre", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.TransfererTitre(_ob_a0, _ob_a1, _ob_a2, _ob_a3, _ob_a4, _ob_a5);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/ConsulterBourse:1.0
    //
    public Evolution
    ConsulterBourse(String _ob_a0)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("ConsulterBourse", true);
                    out.write_string(_ob_a0);
                    in = _invoke(out);
                    Evolution _ob_r = EvolutionHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("ConsulterBourse", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.ConsulterBourse(_ob_a0);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/getListSociete:1.0
    //
    public Societe[]
    getListSociete()
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getListSociete", true);
                    in = _invoke(out);
                    Societe[] _ob_r = SocieteListHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getListSociete", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getListSociete();
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/getListSocietePourUnParticulier:1.0
    //
    public Societe[]
    getListSocietePourUnParticulier(String _ob_a0,
                                    String _ob_a1)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getListSocietePourUnParticulier", true);
                    out.write_string(_ob_a0);
                    out.write_string(_ob_a1);
                    in = _invoke(out);
                    Societe[] _ob_r = SocieteListHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getListSocietePourUnParticulier", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getListSocietePourUnParticulier(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/getListCompteTitre:1.0
    //
    public CompteDeTitre[]
    getListCompteTitre(String _ob_a0,
                       String _ob_a1,
                       String _ob_a2)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getListCompteTitre", true);
                    out.write_string(_ob_a0);
                    out.write_string(_ob_a1);
                    out.write_string(_ob_a2);
                    in = _invoke(out);
                    CompteDeTitre[] _ob_r = CompteDeTitreListHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getListCompteTitre", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getListCompteTitre(_ob_a0, _ob_a1, _ob_a2);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/getListCompteLiquidite:1.0
    //
    public CompteDeLiquidite[]
    getListCompteLiquidite(String _ob_a0,
                           String _ob_a1)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getListCompteLiquidite", true);
                    out.write_string(_ob_a0);
                    out.write_string(_ob_a1);
                    in = _invoke(out);
                    CompteDeLiquidite[] _ob_r = CompteDeLiquiditeListHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getListCompteLiquidite", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getListCompteLiquidite(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/getListVirement:1.0
    //
    public Virement[]
    getListVirement(String _ob_a0,
                    DateStruct _ob_a1)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getListVirement", true);
                    out.write_string(_ob_a0);
                    DateStructHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    Virement[] _ob_r = VirementListHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getListVirement", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getListVirement(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/getListOrdre:1.0
    //
    public Ordre[]
    getListOrdre(String _ob_a0,
                 DateStruct _ob_a1)
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getListOrdre", true);
                    out.write_string(_ob_a0);
                    DateStructHelper.write(out, _ob_a1);
                    in = _invoke(out);
                    Ordre[] _ob_r = OrdreListHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getListOrdre", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getListOrdre(_ob_a0, _ob_a1);
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }

    //
    // IDL:CorbaObject/CourtierForParticulier/getListCourtier:1.0
    //
    public String[]
    getListCourtier()
    {
        while(true)
        {
            if(!this._is_local())
            {
                org.omg.CORBA.portable.OutputStream out = null;
                org.omg.CORBA.portable.InputStream in = null;
                try
                {
                    out = _request("getListCourtier", true);
                    in = _invoke(out);
                    String[] _ob_r = StringListHelper.read(in);
                    return _ob_r;
                }
                catch(org.omg.CORBA.portable.RemarshalException _ob_ex)
                {
                    continue;
                }
                catch(org.omg.CORBA.portable.ApplicationException _ob_aex)
                {
                    final String _ob_id = _ob_aex.getId();
                    in = _ob_aex.getInputStream();

                    throw new org.omg.CORBA.UNKNOWN("Unexpected User Exception: " + _ob_id);
                }
                finally
                {
                    _releaseReply(in);
                }
            }
            else
            {
                org.omg.CORBA.portable.ServantObject _ob_so = _servant_preinvoke("getListCourtier", _ob_opsClass);
                if(_ob_so == null)
                    continue;
                CourtierForParticulierOperations _ob_self = (CourtierForParticulierOperations)_ob_so.servant;
                try
                {
                    return _ob_self.getListCourtier();
                }
                finally
                {
                    _servant_postinvoke(_ob_so);
                }
            }
        }
    }
}
