// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/CompteDeTitre:1.0
//
final public class CompteDeTitreHelper
{
    public static void
    insert(org.omg.CORBA.Any any, CompteDeTitre val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static CompteDeTitre
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[3];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "numeroCompte";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_string);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "societeListe";
            members[1].type = SocieteListHelper.type();

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "ordreListe";
            members[2].type = OrdreListHelper.type();

            typeCode_ = orb.create_struct_tc(id(), "CompteDeTitre", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:CorbaObject/CompteDeTitre:1.0";
    }

    public static CompteDeTitre
    read(org.omg.CORBA.portable.InputStream in)
    {
        CompteDeTitre _ob_v = new CompteDeTitre();
        _ob_v.numeroCompte = in.read_string();
        _ob_v.societeListe = SocieteListHelper.read(in);
        _ob_v.ordreListe = OrdreListHelper.read(in);
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, CompteDeTitre val)
    {
        out.write_string(val.numeroCompte);
        SocieteListHelper.write(out, val.societeListe);
        OrdreListHelper.write(out, val.ordreListe);
    }
}
