// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/CourtierForParticulier:1.0
//
final public class CourtierForParticulierHolder implements org.omg.CORBA.portable.Streamable
{
    public CourtierForParticulier value;

    public
    CourtierForParticulierHolder()
    {
    }

    public
    CourtierForParticulierHolder(CourtierForParticulier initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = CourtierForParticulierHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        CourtierForParticulierHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return CourtierForParticulierHelper.type();
    }
}
