// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/DateStruct:1.0
//
final public class DateStructHelper
{
    public static void
    insert(org.omg.CORBA.Any any, DateStruct val)
    {
        org.omg.CORBA.portable.OutputStream out = any.create_output_stream();
        write(out, val);
        any.read_value(out.create_input_stream(), type());
    }

    public static DateStruct
    extract(org.omg.CORBA.Any any)
    {
        if(any.type().equivalent(type()))
            return read(any.create_input_stream());
        else
            throw new org.omg.CORBA.BAD_OPERATION();
    }

    private static org.omg.CORBA.TypeCode typeCode_;

    public static org.omg.CORBA.TypeCode
    type()
    {
        if(typeCode_ == null)
        {
            org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init();
            org.omg.CORBA.StructMember[] members = new org.omg.CORBA.StructMember[7];

            members[0] = new org.omg.CORBA.StructMember();
            members[0].name = "year";
            members[0].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[1] = new org.omg.CORBA.StructMember();
            members[1].name = "month";
            members[1].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[2] = new org.omg.CORBA.StructMember();
            members[2].name = "day";
            members[2].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[3] = new org.omg.CORBA.StructMember();
            members[3].name = "hour";
            members[3].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[4] = new org.omg.CORBA.StructMember();
            members[4].name = "minute";
            members[4].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[5] = new org.omg.CORBA.StructMember();
            members[5].name = "second";
            members[5].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            members[6] = new org.omg.CORBA.StructMember();
            members[6].name = "microsecond";
            members[6].type = orb.get_primitive_tc(org.omg.CORBA.TCKind.tk_long);

            typeCode_ = orb.create_struct_tc(id(), "DateStruct", members);
        }

        return typeCode_;
    }

    public static String
    id()
    {
        return "IDL:CorbaObject/DateStruct:1.0";
    }

    public static DateStruct
    read(org.omg.CORBA.portable.InputStream in)
    {
        DateStruct _ob_v = new DateStruct();
        _ob_v.year = in.read_long();
        _ob_v.month = in.read_long();
        _ob_v.day = in.read_long();
        _ob_v.hour = in.read_long();
        _ob_v.minute = in.read_long();
        _ob_v.second = in.read_long();
        _ob_v.microsecond = in.read_long();
        return _ob_v;
    }

    public static void
    write(org.omg.CORBA.portable.OutputStream out, DateStruct val)
    {
        out.write_long(val.year);
        out.write_long(val.month);
        out.write_long(val.day);
        out.write_long(val.hour);
        out.write_long(val.minute);
        out.write_long(val.second);
        out.write_long(val.microsecond);
    }
}
