// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Evolution:1.0
//
/***/

final public class Evolution implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _ob_id = "IDL:CorbaObject/Evolution:1.0";

    public
    Evolution()
    {
    }

    public
    Evolution(DateStruct date,
              float[] valeur,
              Societe unesociete,
              float[] les5meilleursAchat,
              float[] les5meilleursVente)
    {
        this.date = date;
        this.valeur = valeur;
        this.unesociete = unesociete;
        this.les5meilleursAchat = les5meilleursAchat;
        this.les5meilleursVente = les5meilleursVente;
    }

    public DateStruct date;
    public float[] valeur;
    public Societe unesociete;
    public float[] les5meilleursAchat;
    public float[] les5meilleursVente;
}
