// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/FloatList:1.0
//
final public class FloatListHolder implements org.omg.CORBA.portable.Streamable
{
    public float[] value;

    public
    FloatListHolder()
    {
    }

    public
    FloatListHolder(float[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = FloatListHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        FloatListHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return FloatListHelper.type();
    }
}
