// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Ordre:1.0
//
final public class OrdreHolder implements org.omg.CORBA.portable.Streamable
{
    public Ordre value;

    public
    OrdreHolder()
    {
    }

    public
    OrdreHolder(Ordre initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = OrdreHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        OrdreHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return OrdreHelper.type();
    }
}
