// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/StringList:1.0
//
final public class StringListHolder implements org.omg.CORBA.portable.Streamable
{
    public String[] value;

    public
    StringListHolder()
    {
    }

    public
    StringListHolder(String[] initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = StringListHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        StringListHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return StringListHelper.type();
    }
}
