// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Titre:1.0
//
/***/

final public class Titre implements org.omg.CORBA.portable.IDLEntity
{
    private static final String _ob_id = "IDL:CorbaObject/Titre:1.0";

    public
    Titre()
    {
    }

    public
    Titre(String numero,
          String numeroSociete)
    {
        this.numero = numero;
        this.numeroSociete = numeroSociete;
    }

    public String numero;
    public String numeroSociete;
}
