// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Titre:1.0
//
final public class TitreHolder implements org.omg.CORBA.portable.Streamable
{
    public Titre value;

    public
    TitreHolder()
    {
    }

    public
    TitreHolder(Titre initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = TitreHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        TitreHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return TitreHelper.type();
    }
}
