// **********************************************************************
//
// Generated by the ORBacus IDL to Java Translator
//
// Copyright (c) 2005
// IONA Technologies, Inc.
// Waltham, MA, USA
//
// All Rights Reserved
//
// **********************************************************************

// Version: 4.3.2

package CorbaObject;

//
// IDL:CorbaObject/Virement:1.0
//
final public class VirementHolder implements org.omg.CORBA.portable.Streamable
{
    public Virement value;

    public
    VirementHolder()
    {
    }

    public
    VirementHolder(Virement initial)
    {
        value = initial;
    }

    public void
    _read(org.omg.CORBA.portable.InputStream in)
    {
        value = VirementHelper.read(in);
    }

    public void
    _write(org.omg.CORBA.portable.OutputStream out)
    {
        VirementHelper.write(out, value);
    }

    public org.omg.CORBA.TypeCode
    _type()
    {
        return VirementHelper.type();
    }
}
